More fixes for conflicts
Signed-off-by: Bob Weinand <bob.weinand@datadoghq.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -15,10 +15,13 @@ workflows:
             - run:
                 name: Generate custom steps for test_web and test_integrations
                 command: |
-                  START=$(grep -Pzom1 '\A(.*+\n)+?\s++integration_snapshots:(.*+\n)+?(?=(\s++)- run.*\n(\3.*+\n)*?\s++name: Run tests)' .circleci/continue_config.yml)
-                  END=$(grep -Pzom1 'integration_snapshots:[^\0]+?(\s+)- run:(\1.+)+?name: Run tests[^\0]+?\K(?=\1\S)(.*\n)++' .circleci/continue_config.yml)
+                  cp .circleci/continue_config.yml ../continue_config.yml
                   
-                  command=$(grep -Pzo 'integration_snapshots:[^\0]+?(\s+)- run:(\1.+)+?name: Run tests\K[^\0]+?(?=\1\S)' .circleci/continue_config.yml)
+                  for testsuite in integration_snapshots integration_tests; do
+                  START=$(grep -Pzom1 '\A(.*+\n)+?\s++'"$testsuite"':(.*+\n)+?(?=(\s++)- run.*\n(\3.*+\n)*?\s++name: Run.*tests)' ../continue_config.yml)
+                  END=$(grep -Pzom1 "$testsuite"':[^\0]+?(\s+)- run:(\1.+)+?name: Run.*tests[^\0]+?\K(?=\1\S)(.*\n)++' ../continue_config.yml)
+                  
+                  command=$(grep -Pzo "$testsuite"':[^\0]+?(\s+)- run:(\1.+)+?name: Run.*tests\K[^\0]+?(?=\1\S)' ../continue_config.yml)
                   command=${command//$'\n'/$'\n      '}
                   
                   {
@@ -29,10 +32,9 @@ workflows:
                   PHP_VERSIONS=($(grep -Po "(?<=TEST_${type}_)[0-9]+" Makefile))
                   ALL_TASKS=($(grep -Pzo 'TEST_'"${type}"'_[0-9]+[^\0]+?\n(?![\t#])' Makefile | grep -avE '^#' | grep -a '\t' | sed -e 's/\t//g' -e 's/\s*\\//g' | sort | uniq))
 
-                  parallel_index=0
                   for task in "${ALL_TASKS[@]}"; do
-                  targeted_command=${command/\<< parameters.make_target >>/$task}
-                  targeted_command=${targeted_command/$'|\n'/$'|\n                  echo $$ >/tmp/background-$task.pid; trap \'rv=$?; [ $rv -eq 0 ] || touch /tmp/background-error; exit $rv\' INT TERM EXIT; export TEST_PARALELISM_INDEX='"$((++parallel_index))"$'\n'}
+                  targeted_command=${command//\<< parameters.make_target >>/$task}
+                  targeted_command=${targeted_command/$'|\n'/$'|\n                  echo $$ >/tmp/background-'$task$'.pid; trap \'rv=$?; [ $rv -eq 0 ] || touch /tmp/background-error; exit $rv\' INT TERM EXIT\n'}
                   cat \<<EOT
                         - when:
                             condition:
@@ -63,6 +65,7 @@ workflows:
                               - run:
                                   name: Await all tests
                                   command: |
+                                    sleep 10 # wait for all background tasks to have launched
                                     for f in \$(echo /tmp/background-*); do
                                       tail --pid=\$(cat \$f) -f /dev/null || true
                                     done
@@ -79,6 +82,7 @@ workflows:
                   EOT
                   echo "$END"
                   } > ../continue_config.yml
+                  done
 
           base-revision: master
           config-path: ../continue_config.yml
