flow framework tests

diff --git a/dockerfiles/frameworks/src/Dockerfile b/dockerfiles/frameworks/src/Dockerfile
--- a/dockerfiles/frameworks/src/Dockerfile
+++ b/dockerfiles/frameworks/src/Dockerfile
@@ -32,9 +32,12 @@ RUN set -xe; \
         php-amqp \
         php-dev \
         php-pear \
+        php-bcmath \
         curl \
         vim; \
-    pecl install redis
+    pecl install redis; \
+    git config --global user.email "example@example.com"; \
+    git config --global user.name "Patch Maker";
 
 RUN set -xe; \
     php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');";\
@@ -54,20 +57,20 @@ FROM base AS symfony
 ENV COMPOSER_MEMORY_LIMIT -1
 ARG SYMFONY_VERSION_TAG=v4.3.4
 
+
 RUN set -xe; \
     git clone --depth 1 --branch ${SYMFONY_VERSION_TAG} https://github.com/symfony/symfony /home/symfony; \
     cd /home/symfony; \
     composer update --prefer-dist; \
     php ./phpunit install
-WORKDIR /home/symfony
-ADD symfony_${SYMFONY_VERSION_TAG}.patch ./
 
+WORKDIR /home/symfony/
+ADD symfony_${SYMFONY_VERSION_TAG}.patch ./
 RUN set -xe; \
-  git add -f vendor; \
-  git config --global user.email "you@example.com"; \
-  git config --global user.name "Your Name"; \
-  git commit -m "vendor"; \
-  git apply *.patch
+    # add vendor to git to allow easy patching of vendor files too
+    git add -f vendor; \
+    git commit -m "vendor"; \
+    git apply *.patch
 
 ENV SYMFONY_DEPRECATIONS_HELPER=disabled=1
 ADD symfony_run.sh ./
@@ -77,10 +80,53 @@ FROM base AS laravel
 ARG LARAVEL_VERSION_TAG=v5.8.17
 RUN set -xe; \
     git clone --depth 1 --branch ${LARAVEL_VERSION_TAG} https://github.com/laravel/framework /home/laravel; \
-    apt-get -y install php-bcmath;
-
-RUN set -xe; \
     cd /home/laravel; \
     export COMPOSER_MEMORY_LIMIT=-1; \
     composer install --prefer-dist
 WORKDIR /home/laravel
+
+FROM base AS flow
+ARG FLOW_VERSION_TAG=5.2.6
+ARG FLOW_BUILD_TOOLS_VERISON=5.2
+RUN set -xe; \
+    git clone https://github.com/neos/flow-development-distribution.git -b ${FLOW_BUILD_TOOLS_VERISON} /home/flow; \
+    # git clone --depth 1 --branch ${FLOW_VERSION_TAG} https://github.com/neos/flow-development-collection /home/flow; \
+    cd /home/flow; \
+    composer update --no-progress --no-interaction
+
+WORKDIR /home/flow
+RUN set -xe; \
+    mkdir -p ../../neos/; \
+    git clone --depth 1 --branch ${FLOW_VERSION_TAG} https://github.com/neos/flow-development-collection ../../neos/flow-development-collection; \
+    export NEOS_TARGET_REPOSITORY=neos/flow-development-collection; \
+    export NEOS_TARGET_VERSION=5.2; \
+    export TRAVIS_REPO_SLUG=neos/flow-development-collection; \
+    php Build/BuildEssentials/TravisCi/ComposerManifestUpdater.php .
+RUN set -xe; \
+    sed -e 's/dev-travis as //g' -i composer.json; \
+    composer update --no-progress --no-interaction; \
+    rm -f Configuration/Routes.yaml; \
+    cp Configuration/Settings.yaml.example Configuration/Settings.yaml; \
+    set -e 's/127.0.0.1/mysql/g' -i Configuration/Settings.yaml; \
+    Build/BuildEssentials/TravisCi/SetupDatabase.sh; \
+    cp Configuration/Settings.yaml Configuration/Testing/; \
+    FLOW_CONTEXT=Testing/Behat ./flow behat:setup; \
+    apt-get install -y default-mysql-client
+
+ADD flow/30.tz.ini /etc/php/7.3/cli/conf.d/30-tz.ini
+ADD flow/Settings.yaml Configuration/Settings.yaml
+ADD flow/Settings.yaml Configuration/Testing/Settings.yaml
+ADD flow/run.sh ./
+# RUN set -xe; \
+
+# CMD ["bin/phpunit", "--colors", "-c", "Build/BuildEssentials/PhpUnit/UnitTests.xml"]
+# CMD ["bin/behat", "--ansi", "--stop-on-failure", "-f", "progress", "-c", "Packages/Framework/Neos.Flow/Tests/Behavior/behat.yml.dist"]
+# CMD ["bin/phpunit",  "--colors",  "--stop-on-failure",  "-c", "Build/BuildEssentials/PhpUnit/FunctionalTests.xml", "--testsuite", "Framework tests"]
+CMD [ "./run.sh" ]
+# RUN bin/phpunit --colors -c Build/BuildEssentials/PhpUnit/UnitTests.xml
+#
+
+RUN set -xe; \
+  echo "deb https://packages.sury.org/php/ buster main" | tee /etc/apt/sources.list.d/php.list; \
+  curl -L -o - https://packages.sury.org/php/apt.gpg | apt-key add -;\
+  apt-get update
